// lib/museum_data.dart

/// Bu liste muze.gov.tr adresinden 25 Ocak 2026 tarihinde çekilmiştir.
/// Müzekart geçerli olan kesin noktaları içerir.

final List<String> officialMuseums = [
  "Batı Cephesi Karargahı Müzesi",
  "ADAM MICKIEWICZ MÜZESİ",
  "Adana Arkeoloji Müzesi",
  "Adana Atatürk Evi Müzesi",
  "Adıyaman Müzesi",
  "Afrodisias Müzesi ve Örenyeri",
  "Afyonkarahisar Müzesi",
  "Agora Örenyeri",
  "Ahlat Müzesi",
  "Ahlat Selçuklu Mezarlığı",
  "Aigai Örenyeri",
  "Aizanoi Örenyeri",
  "Akdamar Anıt Müzesi",
  "Aksaray Manastır Vadisi Örenyeri",
  "Aksaray Müzesi",
  "AKŞEHİR NASRETTİN HOCA ARKEOLOJİ VE ETNOGRAFYA MÜZESİ",
  "AKŞEMSETTİN TÜRBESİ",
  "Alabanda Örenyeri",
  "Alacahöyük Müzesi ve Örenyeri",
  "Alaeddin Yavaşça Müze Evi",
  "Alahan Manastırı",
  "Alanya Atatürk Evi Müzesi",
  "Alanya Kalesi",
  "Alanya Müzesi",
  "Alaşehir Örenyeri",
  "Alexandria Troas Örenyeri",
  "Alinda Örenyeri",
  "Amasra Müzesi",
  "Amasya Müzesi",
  "Amintas Kaya Mezarı",
  "Anadolu Medeniyetleri Müzesi",
  "Anamur Müzesi",
  "Anavarza Örenyeri",
  "Anemurium Örenyeri",
  "Ani Örenyeri",
  "Antalya Atatürk Evi Müzesi",
  "ANTALYA ETNOGRAFYA MÜZESİ",
  "Antalya Müzesi",
  "Antalya Nekropol Müzesi",
  "ANTIOCHEIA ÖRENYERİ",
  "Apollon Smintheion Örenyeri",
  "ARSEMEIA Örenyeri",
  "Arykanda Örenyeri",
  "Aşık Veysel Müzesi",
  "Aşıklı Höyük",
  "Aslantepe Örenyeri",
  "Aspendos Örenyeri",
  "Assos Örenyeri",
  "Atatürk Evi Müzesi",
  "Atatürk ve Etnografya Müzesi",
  "Atatürk, Redif ve Etnografya Müzesi",
  "Atlas 1948 İstanbul Sinema Müzesi",
  "Av Köşkü Saray Müzesi",
  "Ayasofya Tarih ve Deneyim Müzesi",
  "Ayasuluk - St.Jean Örenyeri",
  "Ayasuluk KALESİ",
  "Aydın Arkeoloji Müzesi",
  "Aziz (St.) Nikolaos Anıt Müzesi",
  "AZİZ MERCURIUS YERALTI ŞEHRİ",
  "Bafra Müzesi",
  "Bandırma Müzesi",
  "BAYBURT MÜZESİ",
  "Bergama Akropolü",
  "Bergama Asklepion Örenyeri",
  "Bergama Kızılavlu",
  "Bergama Müzesi",
  "Beşkonaklar Etnografya Müzesi ve Geleneksel Malatya Evi",
  "Bilecik Müzesi",
  "Birgi Çakırağa Konağı",
  "Bitlis Etnografya Müzesi",
  "Blaundos Örenyeri",
  "Bodrum Antik Tiyatrosu",
  "Bodrum Mausoleium Anıt Müzesi",
  "Bodrum Serçe Limanı Cam Batığı Sergi Salonu",
  "Bodrum Sualtı Arkeoloji Müzesi",
  "Boğazköy Müzesi",
  "Boğazköy-Hattuşa Örenyeri",
  "Bolu Müzesi",
  "Burdur Müzesi",
  "Bursa Arkeoloji Müzesi",
  "Bursa Atatürk Evi Müzesi",
  "Bursa İznik Göl Bazilikası",
  "Bursa Türk İslam Eserleri Müzesi",
  "Büyük Saray Mozaikleri Müzesi",
  "Cahit Sıtkı Tarancı Evi Etnografya Müzesi",
  "Çanakkale Destanı Tanıtım Merkezi",
  "Çankırı Müzesi",
  "Çatalhöyük Örenyeri",
  "Çavuşin Örenyeri (Çavuşin Kilisesi)",
  "Çavuştepe Kalesi",
  "Cehennemağzı Mağaraları",
  "Çeşme Müzesi",
  "Çevlik Örenyeri",
  "Çini Müzesi",
  "Çorum Müzesi",
  "Cumhuriyet Müzesi",
  "DARA ÖRENYERİ",
  "Denizli Atatürk ve Etnografya Müzesi",
  "Denizli Kent Müzesi",
  "DENİZLİ TRIPOLIS ÖRENYERİ",
  "Derinkuyu Yeraltı Şehri",
  "Didim Apollon Tapınağı",
  "Diyarbakır Arkeoloji  Müzesi",
  "Doğa Tarihi Müzesi",
  "Edirne Hıdırlık Tabya Balkan Tarihi Müzesi",
  "Edirne Müzesi",
  "Efes Deneyim Müzesi",
  "Efes Müzesi",
  "Efes Örenyeri",
  "Efes Örenyeri-Yamaçevler",
  "El Nazar Kilisesi",
  "Elazığ Müzesi",
  "ELBİSTAN ŞEHİR MÜZESİ",
  "Elmalı Müzesi",
  "Ereğli Müzesi",
  "Ermenek Ahmet Keleşoğlu Arkeoloji ve Etnografya Müzesi",
  "Erzincan Müzesi",
  "Erzurum Atatürk Evi Müzesi",
  "Erzurum Kalesi",
  "Erzurum Müzesi",
  "Erzurum Resim Heykel Müzesi",
  "Eti Arkeoloji Müzesi",
  "Etnografya Müzesi",
  "Fethiye Gemile Adası",
  "Fethiye Kayaköy Örenyeri",
  "Fethiye Letoon Örenyeri",
  "Fethiye Müzesi",
  "Fethiye Müzesi",
  "Fethiye Pınara Örenyeri",
  "Fethiye Tlos Örenyeri",
  "FİLYOS(TIOS) ÖRENYERİ",
  "GALATA KULESİ",
  "Galata Mevlevihanesi Müzesi",
  "Gazi Müzesi",
  "Gaziantep Arkeoloji Müzesi",
  "Gaziantep Kalesi",
  "GERMANICIA MOZAİKLİ ALAN",
  "Giresun Müzesi",
  "Göbeklitepe Örenyeri",
  "GORDİON MÜZESİ",
  "Göreme Örenyeri",
  "Gözne Kalesi",
  "Gülşehir-St.Jean Kilisesi",
  "Gümüşhane Müzesi",
  "Gümüşler Manastırı ve Yeraltı Şehri",
  "Güpgüpoğlu Konağı Etnografya Müzesi",
  "Hacıbektaş Müzesi",
  "HAFIZA 15 TEMMUZ MÜZESİ",
  "Haleplibahçe Mozaik Müzesi",
  "Hamidiye Tabyası ve Çanakkale Savaşları Tarihi Müzesi",
  "HARPUT KALESİ",
  "Harran Örenyeri",
  "Hasankeyf Müzesi ve Örenyeri",
  "Hatay Arkeoloji Müzesi",
  "HATAY NECMİ ASFUROĞLU ARKEOLOJİ MÜZESİ",
  "Hazeranlar Konağı",
  "Hierapolis (Pamukkale) Arkeoloji Müzesi",
  "Hierapolis (Pamukkale) Örenyeri",
  "Hoşap Kalesi",
  "IASSOS ÖRENYERİ",
  "Ihlara Vadisi Örenyeri",
  "İshak Paşa Sarayı",
  "İslam Bilim ve Teknoloji Tarihi Müzesi",
  "Isparta Müzesi",
  "İSTANBUL ARKEOLOJİ MÜZELERİ",
  "İstanbul Havalimanı Müzesi",
  "İzmir Arkeoloji Müzesi",
  "İzmir Atatürk Müzesi",
  "İzmir Kültür Sanat Fabrikası",
  "İzmir Resim Heykel Müzesi",
  "İznik Müzesi",
  "Kahramankazan 15 Temmuz Demokrasi Müzesi",
  "Kahramanmaraş Müzesi",
  "Kahta Yenikale Örenyeri",
  "Kaman Kalehöyük Arkeoloji Müzesi",
  "Kanlı Divane Örenyeri",
  "Karacasu Etnografya Müzesi",
  "Karadeniz  Ereğli Müzesi",
  "Karahantepe Örenyeri",
  "Karain Mağarası",
  "Karaman Müzesi",
  "Karanlık Kilise (Göreme)",
  "Karatay (Çini Eserler) Müzesi",
  "Karatepe Aslantaş Müzesi ve Örenyeri",
  "KARS Kafkas Cephesi Harp Tarihi Müzesi",
  "Kars Müzesi",
  "Kastabala Örenyeri",
  "Kastamonu Müzesi",
  "Kaunos Örenyeri",
  "Kaymaklı Yeraltı Şehri",
  "Kayseri Arkeoloji Müzesi",
  "Kayseri Atatürk Evi Müzesi",
  "Keskin Sulu Mağara Yeraltı Şehri",
  "Kibyra Örenyeri",
  "Kilis Müzesi",
  "Kilitbahir Kale Müzesi",
  "Kırklareli Müzesi",
  "Kırşehir Müzesi",
  "Kız Kulesi",
  "Klaros Örenyeri",
  "Klazomenai Örenyeri",
  "Kocaeli Arkeoloji Müzesi",
  "Konuralp Müzesi",
  "Konya Arkeoloji Müzesi",
  "Konya Atatürk Evi Müzesi",
  "Konya Etnografya Müzesi",
  "Kossouth Evi Müzesi",
  "Küçük Ayvasıl St. Anna Kilisesi",
  "Kültepe Örenyeri",
  "Kuruköprü  Anıt Müzesi ve Geleneksel Adana Evi",
  "Kütahya Müzesi",
  "Kuva-Yi Milliye Müzesi",
  "Labraunda Örenyeri",
  "Lagina Örenyeri",
  "LAODIKEIA ÖRENYERİ",
  "Latifoğlu Konağı",
  "Likya Uygarlıkları Müzesi ve Andriake Örenyeri",
  "Limyra Örenyeri",
  "Livapaşa Konağı Etnografya Müzesi",
  "Maden Müzesi",
  "MAGNESIA ÖRENYERİ",
  "Malatya Atatürk Anı Evi ve Etnoğrafya Müzesi",
  "Malatya Müzesi",
  "Malazgirt Müzesi",
  "Mamure Kalesi",
  "Manisa Akhisar Müzesi ve Akhisar Tepe Mezarlığı",
  "Manisa Müzesi",
  "Mardin Müzesi",
  "Marmaris Müzesi",
  "Mazı Yeraltı Şehri",
  "Mehmet Akif Ersoy Hatıra Evi",
  "Mehmet Cabir Alper Arkeoloji Müzesi",
  "Mersin Atatürk Evi Müzesi",
  "Mersin Kız Kalesi",
  "Mersin Müzesi",
  "Mersin Tarsus Müzesi",
  "Meryem Ana Manastırı",
  "Metropolis Örenyeri",
  "Mevlana Müzesi",
  "MEVLEVİHANE MÜZESİ",
  "Midas Yazılıkaya Örenyeri",
  "Milas Beçin Kalesi ve Örenyeri",
  "Milas Euromos Örenyeri",
  "Milas İassos Balık Pazarı Müzesi",
  "Milas Taş Eserler Müzesi",
  "Milas Uzunyuva Anıt Mezarı ve Müze Kompleksi",
  "Milet Müzesi",
  "Milet Örenyeri",
  "Mucur Yeraltı Şehri",
  "Mudanya Mütareke Evi Müzesi",
  "Muğla Knidos Örenyeri",
  "Muğla Müzesi",
  "Muş Müzesi",
  "Myra Örenyeri",
  "Namazgâh Tabyası Müzesi",
  "Necmi İğe Evi Etnografya Müzesi",
  "Nemrut Örenyeri",
  "Nevşehir Hacıbektaş Arkeoloji ve Etnografya Müzesi",
  "Nevşehir Hacıbektaş Atatürk Evi Müzesi",
  "Nevşehir Müzesi",
  "Niğde Andaval Örenyeri",
  "Niğde Müzesi",
  "Nilüfer Hatun İmareti Türk İslam Eserleri Müzesi",
  "Nysa Sultanhisar Örenyeri",
  "Ödemiş Müzesi",
  "Olympos Örenyeri",
  "Ordu Müzesi",
  "Osman Hamdi Bey Müzesi",
  "Osmaniye Müzesi",
  "Osmanlı Evi Müzesi",
  "Özkonak Yeraltı Şehri",
  "Patara Örenyeri",
  "Perge Örenyeri",
  "PERRE Örenyeri",
  "Pessinus Örenyeri",
  "Phaselis Örenyeri",
  "Priene Örenyeri",
  "Resim Heykel Müzesi",
  "Rize Atatürk Evi Müzesi",
  "Rize Müzesi",
  "Roma Hamamı Örenyeri",
  "RUMELİ HİSARI",
  "Rumkale Örenyeri",
  "Sagalassos Örenyeri",
  "Sakarya Müzesi",
  "Samsun Müzesi",
  "Şanlıurfa Arkeoloji Müzesi",
  "Şanlıurfa Kalesi",
  "Saratlı Kırkgöz Yeraltı Şehri",
  "Sardes Örenyeri",
  "SARIKAYA ROMA HAMAMI",
  "Sedir Adası Örenyeri",
  "Side Müzesi",
  "Side Örenyeri",
  "Silifke Astım Mağarası",
  "Silifke Atatürk Evi ve Etnografya Müzesi",
  "Silifke Ayatekla Örenyeri",
  "Silifke Cennet Cehennem Obrukları",
  "Silifke Müzesi",
  "Silifke Narlıkuyu Mozaik Müzesi",
  "Silvan Atatürk Evi Müzesi",
  "Simena Örenyeri",
  "Sinop Arslantorunlar Etnografya Müzesi",
  "Sinop Müzesi",
  "Sivas Arkeoloji Müzesi",
  "Sivas Atatürk ve Kongre Müzesi",
  "SOBESSOS ÖRENYERİ",
  "Sofraz Anıt Mezarı",
  "Söğüt Ertuğrul Gazi Müzesi",
  "St. Pierre Anıt Müzesi",
  "St. SIMON MANASTIRI",
  "STRATONIKEIA ÖRENYERİ",
  "Sümela Manastırı",
  "Syedra Örenyeri",
  "Taksiyarhis Anıt Müzesi",
  "Tarihi Cezaevi",
  "Tarsus St. Paul Anıt Müzesi",
  "Tarsus St. Paul Kuyusu",
  "Tatlarin Yeraltı Şehri",
  "Tekirdağ Muratlı Atatürk Evi Müzesi",
  "Tekirdağ Müzesi",
  "Teos Örenyeri",
  "Termessos Örenyeri",
  "Tire Müzesi",
  "Tokat Atatürk Evi ve Etnografya Müzesi",
  "Tokat Müzesi",
  "Trabzon Müzesi (Kostaki Konağı)",
  "Troya Müzesi",
  "Troya Örenyeri",
  "Tunceli Müzesi",
  "Türk İslam Eserleri Müzesi",
  "Türk İslam Eserleri ve Etnografya Müzesi",
  "Türk ve İslam Eserleri Müzesi",
  "Uluborlu Müzesi",
  "Ürgüp Müzesi",
  "Uşak Müzesi",
  "Uzuncaburç Örenyeri",
  "Van Kalesi",
  "Van Müzesi",
  "Xanthos Örenyeri",
  "Yalvaç Müzesi",
  "Yenişehir Şemaki Evi Müzesi",
  "Yesemek Örenyeri",
  "Yeşilhisar Soğanlı Örenyeri",
  "Yörük Ali Efe Evi Müzesi",
  "Yozgat Müzesi",
  "Zeki Müren Sanat Müzesi",
  "Zelve - Paşabağlar Örenyeri",
  "Zeugma Mozaik Müzesi",
  "ZEUGMA ÖRENYERİ",
  "Ziya Gökalp Müzesi",
];
final List<String> englishAliases = [
  "ephesus", "efes",
  "hierapolis", "pamukkale",
  "hagia sophia", "ayasofya",
  "topkapi palace", "topkapi",
  "galata tower", "galata",
  "maiden's tower", "kiz kulesi", "maidens tower",
  "basilica cistern", "yerebatan",
  "troy", "troya", "truva",
  "pergamon", "bergama",
  "aspendos", "aspendus",
  "phaselis", "faselis",
  "olympos", "olimpos",
  "myra", "demre",
  "st nicholas", "noel baba",
  "sumela", "sumela monastery",
  "akdamar", "akdamar church",
  "mount nemrut", "nemrut",
  "gobeklitepe", "gobekli tepe", "potbelly hill",
  "zeugma", "belkis",
  "cappadocia", "kapadokya",
  "goreme", "goreme open air",
  "kaymakli", "derinkuyu",
  "ihlara valley", "ihlara",
  "zilli", "sagalassos", // Eklenenler
  "anitkabir",
];

// Metin Temizleme Fonksiyonu
String normalizeString(String input) {
  var text = input.toLowerCase();
  text = text.replaceAll('ç', 'c');
  text = text.replaceAll('ğ', 'g');
  text = text.replaceAll('ı', 'i');
  text = text.replaceAll('ö', 'o');
  text = text.replaceAll('ş', 's');
  text = text.replaceAll('ü', 'u');
  text = text.replaceAll('İ', 'i');
  text = text.replaceAll('.', '');
  text = text.replaceAll(',', '');
  text = text.replaceAll("'", "");
  text = text.replaceAll('-', ' ');
  return text.trim();
}

// KATI KURAL EŞLEŞTİRME FONKSİYONU
bool checkIfMuseumPassValid(String placeName) {
  final normalizedInput = normalizeString(placeName);

  // 1. Resmi Listede Ara (Senin çektiğin 353 veri)
  for (var museum in officialMuseums) {
    final normalizedMuseum = normalizeString(museum);
    // İsimler birbirini içeriyor mu?
    if (normalizedInput.contains(normalizedMuseum) ||
        normalizedMuseum.contains(normalizedInput)) {
      // "Van Müzesi" ile "Van" kelimesinin karışmaması için uzunluk kontrolü
      if (normalizedInput.length > 3) return true;
    }
  }

  // 2. İngilizce/Alternatif Listede Ara
  for (var alias in englishAliases) {
    if (normalizedInput.contains(alias)) {
      return true;
    }
  }

  return false;
}
